blueprint:
  name: Philips Hue Wall Module
  author: Martin Groeneveld
  source_url: https://raw.githubusercontent.com/groveld/home-assistant/refs/heads/main/homeassistant/blueprints/automation/philips_hue_wall_module.yaml
  description: >
    This blueprint allows you to use a Philips Hue Wall Module (RDM001 and RDM004)
    to trigger automations in Home Assistant. You need to have the module paired
    to your Home Assistant Zigbee integration (ZHA). You might need to configure
    the module depending on which physical switch is used (single/double and
    rocker/push). See https://zigbee.blakadder.com/Philips_RDM001.html and
    https://community.home-assistant.io/t/how-to-configure-the-philips-hue-wall-module-to-use-push-button-momentary-type-wall-switches-zha/451125/13
    for more information.
  domain: automation
  input:
    remote:
      name: Remote
      description: Signify switch to use
      selector:
        device:
          filter:
            - integration: zha
              manufacturer: Signify Netherlands B.V.
              model: RDM001
            - integration: zha
              manufacturer: Signify Netherlands B.V.
              model: RDM004
    left_press: &action_input
      name: Left Press
      description: Left press
      default: []
      selector:
        action: null
    left_short_release:
      <<: *action_input
      name: Left Short Release
      description: Left Short Release
    left_double_press:
      <<: *action_input
      name: Left Double Press
      description: Left Double Press
    left_triple_press:
      <<: *action_input
      name: Left Triple Press
      description: Left Triple Press
    left_quadruple_press:
      <<: *action_input
      name: Left Quadruple Press
      description: Left Quadruple Press
    left_quintuple_press:
      <<: *action_input
      name: Left Quintuple Press
      description: Left Quintuple Press
    left_hold:
      <<: *action_input
      name: Left Hold
      description: Left Hold
    left_long_release:
      <<: *action_input
      name: Left Long Release
      description: Left Long Release
    right_press:
      <<: *action_input
      name: Right Press
      description: Right press
    right_short_release:
      <<: *action_input
      name: Right Short Release
      description: Right Short Release
    right_double_press:
      <<: *action_input
      name: Right Double Press
      description: Right Double Press
    right_triple_press:
      <<: *action_input
      name: Right Triple Press
      description: Right Triple Press
    right_quadruple_press:
      <<: *action_input
      name: Right Quadruple Press
      description: Right Quadruple Press
    right_quintuple_press:
      <<: *action_input
      name: Right Quintuple Press
      description: Right Quintuple Press
    right_hold:
      <<: *action_input
      name: Right Hold
      description: Right Hold
    right_long_release:
      <<: *action_input
      name: Right Long Release
      description: Right Long Release

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote

mode: single
max_exceeded: silent

action:
  - choose:
      - conditions: '{{ trigger.event.data.command == "left_press" }}'
        sequence: !input "left_press"
      - conditions: '{{ trigger.event.data.command == "left_short_release" }}'
        sequence: !input "left_short_release"
      - conditions: '{{ trigger.event.data.command == "left_double_press" }}'
        sequence: !input "left_double_press"
      - conditions: '{{ trigger.event.data.command == "left_triple_press" }}'
        sequence: !input "left_triple_press"
      - conditions: '{{ trigger.event.data.command == "left_quadruple_press" }}'
        sequence: !input "left_quadruple_press"
      - conditions: '{{ trigger.event.data.command == "left_quintuple_press" }}'
        sequence: !input "left_quintuple_press"
      - conditions: '{{ trigger.event.data.command == "left_hold" }}'
        sequence: !input "left_hold"
      - conditions: '{{ trigger.event.data.command == "left_long_release" }}'
        sequence: !input "left_long_release"
      - conditions: '{{ trigger.event.data.command == "right_press" }}'
        sequence: !input "right_press"
      - conditions: '{{ trigger.event.data.command == "right_short_release" }}'
        sequence: !input "right_short_release"
      - conditions: '{{ trigger.event.data.command == "right_double_press" }}'
        sequence: !input "right_double_press"
      - conditions: '{{ trigger.event.data.command == "right_triple_press" }}'
        sequence: !input "right_triple_press"
      - conditions: '{{ trigger.event.data.command == "right_quadruple_press" }}'
        sequence: !input "right_quadruple_press"
      - conditions: '{{ trigger.event.data.command == "right_quintuple_press" }}'
        sequence: !input "right_quintuple_press"
      - conditions: '{{ trigger.event.data.command == "right_hold" }}'
        sequence: !input "right_hold"
      - conditions: '{{ trigger.event.data.command == "right_long_release" }}'
        sequence: !input "right_long_release"
